#!/bin/bash

DIFF="git diff --cached --name-only --diff-filter=ACM"
TEX_CHANGED=false

while IFS= read -r pathspec; do
  if [[ $pathspec = *".tex" ]]; then
    TEX_CHANGED=true
    printf "\x1b[33m*\x1b[37m $pathspec\x1b[0m\n"
    latexindent -s -w -m -l=.latexindent.yaml $pathspec
  fi
done < <($DIFF)

if [ $TEX_CHANGED = true ]; then
  rm -f *.bak* **/*.bak* *indent.log >/dev/null 2>/dev/null
  make label
  git add *.tex
fi
