name: CI

on:
  push:

permissions:
  contents: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tex_modules
            bin

      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: small
          run: python3 bin/build-all.py

      - name: Release PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            minimath.pdf
            minimath.nc.pdf
            minimath.np.pdf
            minimath.np.nc.pdf
