name: CI

on:
  push:

permissions:
  contents: write

jobs:
  checkhealth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn checkhealth
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: small
          run: |
            cd tex
            python3 setup.py build --all
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: tex/minimath.pdf
