name: CI

on:
  push:

permissions:
  contents: write

jobs:
  checkhealth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
        working-directory: web
      - run: yarn checkhealth
        working-directory: web
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tex_packages
            bin
      - uses: xu-cheng/texlive-action@v2
        with:
          scheme: small
          run: |
            PYTEX='make PYTEX=bin/pytex'

            ARGS='-Jminimath' ${PYTEX} all
            ARGS='-Jminimath.np.nc --no-proof --no-compute' ${PYTEX} all
            ARGS='-Jminimath.np --no-proof' ${PYTEX} all
            ARGS='-Jminimath.nc --no-compute' ${PYTEX} all

            ARGS='-Jminimath' ${PYTEX} all
            ARGS='-Jminimath.np.nc --no-proof --no-compute' ${PYTEX} all
            ARGS='-Jminimath.np --no-proof' ${PYTEX} all
            ARGS='-Jminimath.nc --no-compute' ${PYTEX} all
      - name: Release PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            minimath.pdf
            minimath.nc.pdf
            minimath.np.pdf
            minimath.np.nc.pdf
